spring.application.name=QuantityMeasurementApp

# H2 DATABASE

spring.datasource.url=jdbc:h2:mem:testdb

spring.datasource.driverClassName=org.h2.Driver

spring.datasource.username=sa

spring.datasource.password=

# H2 CONSOLE

spring.h2.console.enabled=true

# JPA

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

springdoc.swagger-ui.path=/swagger-ui.html

# GOOGLE OAUTH2

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}

spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}

spring.security.oauth2.client.registration.google.scope=openid,profile,email

spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google

# JWT


app.jwt.secret=${JWT_SECRET}

app.jwt.expiration=86400000
